name: Image Optimization

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Optimize Images
        uses: calibreapp/image-actions@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jpegquality: 80
          pngquality: 80
          webpquality: 80

      - name: Upload Optimized Images
        uses: actions/upload-artifact@v2
        with:
          name: optimized-images
          path: .  # Change this path if necessary to point to optimized images

