name: Image Optimization

on:
  pull_request:  # Trigger the workflow only for pull requests
    branches:
      - main

permissions:
  contents: write

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Optimize Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: 80
          pngQuality: 80
          webpQuality: 80
