name: Optimize Assets

on:
  push:
    branches:
      - main

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Image compression using calibreapp/image-actions
    - name: Optimize Images
      uses: calibreapp/image-actions@v2.9.2
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    # Minify CSS using cssnano-cli
    - name: Minify CSS
      run: |
        npm install -g cssnano-cli
        cssnano styles.css styles.min.css

    # Minify JS using terser
    - name: Minify JS
      run: |
        npm install -g terser
        terser script.js -o script.min.js
