name: Image Optimization

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Optimize Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}  # Correct the token input name
          jpegQuality: 80
          pngQuality: 80
          webpQuality: 80
