name: Image Optimization

on:
  pull_request:
    branches:
      - main  # or your target branchh

jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Optimize Images
        uses: calibreapp/image-actions@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          jpegquality: 80
          pngquality: 80
          webpquality: 80
